name: CMake Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        # Test on multiple operating systems
        os: [ubuntu-latest, windows-latest, macos-latest]
        # Test both Debug and Release configurations
        build_type: [Debug, Release]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure CMake
      # Configures the build and enables export of compile commands for debugging
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build Library
      # Compiles the C library
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}
