name: Deploy Doxygen Documentation

on:
  push:
    branches:
      - main # Change to 'master' if needed

# Grant permissions required for GitHub Actions pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps: deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install doxygen graphviz -y

      - name: Generate Documentation
        run: doxygen Doxyfile

      - name: Disable Jekyll processing
        run: touch docs/html/.nojekyll

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This uploads the specific HTML directory directly as the web root
          path: docs/html 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
